/**
 * Default fallback catalog for PalrixShowWebOps
 * Used for offline preview and initial display before token is configured.
 */

export const DEFAULT_PRODUCTS_CSV = `id,productCode,name,categoryName,description,price,originalPrice,baseLikes,baseShares,isNewArrival,isLimitedStock,isMostSold,isMostLiked,badge,badgeClass,sellerId,sizes,colorName,colorCode,imagePath
201,POLO-001,Premium Pique Polo Shirt,Polo Shirts,A refined men's polo shirt cut for a clean fit from breathable piqué cotton. Finished with a classic ribbed collar and two-button placket.,899,1299,142,34,TRUE,FALSE,FALSE,TRUE,Most Liked,badge-liked,palrix-fashion,"S,M,L,XL,XXL",Navy Blue,#1d2e47,images/products/polo_navy.jpg
201,POLO-001,Premium Pique Polo Shirt,Polo Shirts,A refined men's polo shirt cut for a clean fit from breathable piqué cotton. Finished with a classic ribbed collar and two-button placket.,899,1299,142,34,TRUE,FALSE,FALSE,TRUE,Most Liked,badge-liked,palrix-fashion,"S,M,L,XL,XXL",Navy Blue,#1d2e47,images/products/polo_navy_detail.jpg
201,POLO-001,Premium Pique Polo Shirt,Polo Shirts,A refined men's polo shirt cut for a clean fit from breathable piqué cotton. Finished with a classic ribbed collar and two-button placket.,899,1299,142,34,TRUE,FALSE,FALSE,TRUE,Most Liked,badge-liked,palrix-fashion,"S,M,L,XL,XXL",Slate Grey,#8a8d91,images/products/polo_grey.jpg
201,POLO-001,Premium Pique Polo Shirt,Polo Shirts,A refined men's polo shirt cut for a clean fit from breathable piqué cotton. Finished with a classic ribbed collar and two-button placket.,899,1299,142,34,TRUE,FALSE,FALSE,TRUE,Most Liked,badge-liked,palrix-fashion,"S,M,L,XL,XXL",Slate Grey,#8a8d91,images/products/polo_grey_detail.jpg
202,TEE-001,Minimalist Graphic Tee,T-Shirts,An off-duty essential crewneck t-shirt featuring a subtle minimalist chest graphic print. Soft-washed for comfort.,499,799,89,12,TRUE,TRUE,FALSE,FALSE,New Arrival,badge-new,palrix-fashion,"S,M,L,XL",White,#e8e9eb,images/products/tee_white.jpg
202,TEE-001,Minimalist Graphic Tee,T-Shirts,An off-duty essential crewneck t-shirt featuring a subtle minimalist chest graphic print. Soft-washed for comfort.,499,799,89,12,TRUE,TRUE,FALSE,FALSE,New Arrival,badge-new,palrix-fashion,"S,M,L,XL",White,#e8e9eb,images/products/tee_white_detail.jpg
202,TEE-001,Minimalist Graphic Tee,T-Shirts,An off-duty essential crewneck t-shirt featuring a subtle minimalist chest graphic print. Soft-washed for comfort.,499,799,89,12,TRUE,TRUE,FALSE,FALSE,New Arrival,badge-new,palrix-fashion,"S,M,L,XL",Black,#1c1d1f,images/products/tee_black.jpg
202,TEE-001,Minimalist Graphic Tee,T-Shirts,An off-duty essential crewneck t-shirt featuring a subtle minimalist chest graphic print. Soft-washed for comfort.,499,799,89,12,TRUE,TRUE,FALSE,FALSE,New Arrival,badge-new,palrix-fashion,"S,M,L,XL",Black,#1c1d1f,images/products/tee_black_detail.jpg
203,DEN-001,Super-Stretch Slim Jeans,Jeans,"Crafted from premium stretch-cotton denim, these slim-fit jeans provide exceptional flexibility and comfort all day long.",1499,2299,256,87,FALSE,FALSE,TRUE,FALSE,Most Sold,badge-sold,palrix-fashion,"30,32,34,36",Indigo Blue,#253b59,images/products/jeans_blue.jpg
203,DEN-001,Super-Stretch Slim Jeans,Jeans,"Crafted from premium stretch-cotton denim, these slim-fit jeans provide exceptional flexibility and comfort all day long.",1499,2299,256,87,FALSE,FALSE,TRUE,FALSE,Most Sold,badge-sold,palrix-fashion,"30,32,34,36",Charcoal Black,#232426,images/products/jeans_black.jpg
204,CRG-001,Utility Cargo Joggers,Cargo Pants,"A modern take on cargo pants. Features an elasticated waist with drawstring, utility side pockets, and cuffed ankles.",1299,1899,195,64,FALSE,TRUE,FALSE,FALSE,Limited Stock,badge-stock,palrix-fashion,"M,L,XL",Khaki Brown,#9c8b74,images/products/cargo_khaki.jpg
204,CRG-001,Utility Cargo Joggers,Cargo Pants,"A modern take on cargo pants. Features an elasticated waist with drawstring, utility side pockets, and cuffed ankles.",1299,1899,195,64,FALSE,TRUE,FALSE,FALSE,Limited Stock,badge-stock,palrix-fashion,"M,L,XL",Olive Green,#556b2f,images/products/cargo_olive.jpg
205,TRK-001,Comfort Fleece Track Pants,Track Pants,"Premium athletic sweatpants with side stripe details, secure pockets, and a comfortable drawstring elastic waist.",999,1499,312,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"S,M,L,XL",Heather Grey,#b0b3b5,images/products/trackpants_grey.jpg
205,TRK-001,Comfort Fleece Track Pants,Track Pants,"Premium athletic sweatpants with side stripe details, secure pockets, and a comfortable drawstring elastic waist.",999,1499,312,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"S,M,L,XL",Active Black,#161718,images/products/trackpants_black.jpg
206,KF-206,Pakistani Suits & Party Wear,Top & Pent,FABRIC - Top Fabric - Heavy Chanderi With Embroidery Sequence Work. Top Length: Max up to 46 Inner - Heavy Cotton Pent Fabric: Heavy Chanderi With (Elastic) Pent Length: Max up to 40,899,1499,150,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"M,L,XL,XXL",Teal,#008080,images/products/KF-206/KF-206 (1).jpg
206,KF-206,Pakistani Suits & Party Wear,Top & Pent,FABRIC - Top Fabric - Heavy Chanderi With Embroidery Sequence Work. Top Length: Max up to 46 Inner - Heavy Cotton Pent Fabric: Heavy Chanderi With (Elastic) Pent Length: Max up to 40,899,1499,150,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"M,L,XL,XXL",Teal,#008080,images/products/KF-206/KF-206 (2).jpg
206,KF-206,Pakistani Suits & Party Wear,Top & Pent,FABRIC - Top Fabric - Heavy Chanderi With Embroidery Sequence Work. Top Length: Max up to 46 Inner - Heavy Cotton Pent Fabric: Heavy Chanderi With (Elastic) Pent Length: Max up to 40,899,1499,150,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"M,L,XL,XXL",Teal,#008080,images/products/KF-206/KF-206 (3).jpg
206,KF-206,Pakistani Suits & Party Wear,Top & Pent,FABRIC - Top Fabric - Heavy Chanderi With Embroidery Sequence Work. Top Length: Max up to 46 Inner - Heavy Cotton Pent Fabric: Heavy Chanderi With (Elastic) Pent Length: Max up to 40,899,1499,150,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"M,L,XL,XXL",Teal,#008080,images/products/KF-206/KF-206 (4).jpg
206,KF-206,Pakistani Suits & Party Wear,Top & Pent,FABRIC - Top Fabric - Heavy Chanderi With Embroidery Sequence Work. Top Length: Max up to 46 Inner - Heavy Cotton Pent Fabric: Heavy Chanderi With (Elastic) Pent Length: Max up to 40,899,1499,150,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"M,L,XL,XXL",Teal,#008080,images/products/KF-206/KF-206 (5).jpg
206,KF-206,Pakistani Suits & Party Wear,Top & Pent,FABRIC - Top Fabric - Heavy Chanderi With Embroidery Sequence Work. Top Length: Max up to 46 Inner - Heavy Cotton Pent Fabric: Heavy Chanderi With (Elastic) Pent Length: Max up to 40,899,1499,150,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"M,L,XL,XXL",Teal,#008080,images/products/KF-206/KF-206 (6).jpg
206,KF-206,Pakistani Suits & Party Wear,Top & Pent,FABRIC - Top Fabric - Heavy Chanderi With Embroidery Sequence Work. Top Length: Max up to 46 Inner - Heavy Cotton Pent Fabric: Heavy Chanderi With (Elastic) Pent Length: Max up to 40,899,1499,150,110,TRUE,FALSE,TRUE,TRUE,Most Sold,badge-sold,palrix-fashion,"M,L,XL,XXL",Teal,#008080,images/products/KF-206/KF-206 (7).jpg
S1,SAR101,Saree With Blouse Piece,Saree,Pure Bhagalpuri Linen Hand Blocked Wax Batik Print Saree,650,1100,19,25,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Black,Black,images/products/S1/S1_Black_1.jpeg
S1,SAR101,Saree With Blouse Piece,Saree,Pure Bhagalpuri Linen Hand Blocked Wax Batik Print Saree,650,1100,19,25,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Black,Black,images/products/S1/S1_Black_2.jpeg
S1,SAR101,Saree With Blouse Piece,Saree,Pure Bhagalpuri Linen Hand Blocked Wax Batik Print Saree,650,1100,19,25,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Black,Black,images/products/S1/S1_Black_3.jpeg
S1,SAR101,Saree With Blouse Piece,Saree,Pure Bhagalpuri Linen Hand Blocked Wax Batik Print Saree,650,1100,19,25,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Black,Black,images/products/S1/S1_Black_4.jpeg
S1,SAR101,Saree With Blouse Piece,Saree,Pure Bhagalpuri Linen Hand Blocked Wax Batik Print Saree,650,1100,19,25,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Black,Black,images/products/S1/S1_Black_5.jpeg
207,SAR-12,Saree & Blouse Peace,Saree,Soft Mal Chanderi Cotton Handicraft Ajrakh Print Saree with Blouse Piece,630,999,42,19,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Yellow,#FEED21,images/products/207/207_Yellow_1.jpeg
207,SAR-12,Saree & Blouse Peace,Saree,Soft Mal Chanderi Cotton Handicraft Ajrakh Print Saree with Blouse Piece,630,999,42,19,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Yellow,#FEED21,images/products/207/207_Yellow_2.jpeg
207,SAR-12,Saree & Blouse Peace,Saree,Soft Mal Chanderi Cotton Handicraft Ajrakh Print Saree with Blouse Piece,630,999,42,19,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Yellow,#FEED21,images/products/207/207_Yellow_3.jpeg
207,SAR-12,Saree & Blouse Peace,Saree,Soft Mal Chanderi Cotton Handicraft Ajrakh Print Saree with Blouse Piece,630,999,42,19,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Yellow,#FEED21,images/products/207/207_Yellow_4.jpeg
207,SAR-12,Saree & Blouse Peace,Saree,Soft Mal Chanderi Cotton Handicraft Ajrakh Print Saree with Blouse Piece,630,999,42,19,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,Free Size,Yellow,#FEED21,images/products/207/207_Yellow_5.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_1.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_2.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_3.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_4.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_5.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_6.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_7.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_8.jpeg
208,KF-207,Pakistani Suits & Party Wear,Top & Pent,FABRIC -Top Fabric - Heavy French Crep With Embroidery Sequence Work.,1099,1699,117,67,TRUE,TRUE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Beige,#F3D3FA,images/products/208/208_Beige_9.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Red,Red,images/products/209/209_Red_1.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Grey,#808040,images/products/209/209_Grey_2.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Black,Black,images/products/209/209_Black_3.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Red,Red,images/products/209/209_Red_4.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Black,Black,images/products/209/209_Black_5.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Grey,#808040,images/products/209/209_Grey_6.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Grey,#808040,images/products/209/209_Grey_7.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Red,Red,images/products/209/209_Red_8.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Red,Red,images/products/209/209_Red_9.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Black,Black,images/products/209/209_Black_10.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Grey,#808040,images/products/209/209_Grey_11.jpeg
209,KF - 195,Readymade & Top-plazzo,TOP & PALAZZO,Heavy Rayon With Embroidery Work With Full Stichad ( Elastic),699,1100,15,7,TRUE,FALSE,FALSE,FALSE,,,palrix-fashion,"M,L,XL,XXL",Grey,#808040,images/products/209/209_Grey_12.jpeg
`;
